"use client";
import {useEffect,useRef,useState} from "react";import {gsap} from "gsap";import {ScrollTrigger} from "gsap/ScrollTrigger";
import CloudScene from "./CloudScene";import ProjectJourney from "./ProjectJourney";import SmoothScroll from "./SmoothScroll";import WorldAtmosphere from "./WorldAtmosphere";import {CinematicDirector,ContactPaper,FeaturedBook} from "./ThreeUIScenes";
const sections=[["about","About"],["featured","Featured"],["work","Upcoming"],["skills","Toolkit"],["contact","Contact"]];
export default function Portfolio(){const root=useRef<HTMLDivElement>(null);const [menu,setMenu]=useState(false);const [loading,setLoading]=useState(true);const email=process.env.NEXT_PUBLIC_CONTACT_EMAIL;const contactLinks=[
  ["Email",email?`mailto:${email}`:undefined],
  ["GitHub",process.env.NEXT_PUBLIC_GITHUB_URL],
  ["LinkedIn",process.env.NEXT_PUBLIC_LINKEDIN_URL],
  ["Instagram",process.env.NEXT_PUBLIC_INSTAGRAM_URL],
  ["X / Twitter",process.env.NEXT_PUBLIC_X_URL],
].filter((link):link is [string,string]=>Boolean(link[1]));
 useEffect(()=>{let active=true;const minimum=new Promise(resolve=>setTimeout(resolve,1850));Promise.all([document.fonts.ready,minimum]).then(()=>{if(active)setLoading(false)});return()=>{active=false}},[]);
 useEffect(()=>{gsap.registerPlugin(ScrollTrigger);const media=gsap.matchMedia();media.add("(prefers-reduced-motion: no-preference)",()=>{const ctx=gsap.context(()=>{gsap.from(".reveal",{y:24,opacity:0,duration:1,stagger:.12,ease:"power3.out"});gsap.timeline({scrollTrigger:{trigger:".pre-featured-world",start:"top top",end:"bottom bottom",scrub:.18}}).fromTo(".prelude-sky-cool",{opacity:0,scale:1.06,yPercent:5},{opacity:1,scale:1.16,yPercent:-7,ease:"none"},0).fromTo(".prelude-cloud-far",{yPercent:18,scale:1.03},{yPercent:-18,scale:1.18,ease:"none"},0).fromTo(".prelude-cloud-near",{yPercent:38,scale:1.08},{yPercent:-44,scale:1.32,ease:"none"},0).to(".prelude-light",{xPercent:-16,yPercent:12,opacity:.44,ease:"none"},0);gsap.timeline({scrollTrigger:{trigger:".hero",start:"top top",end:"bottom top",scrub:.16}}).to(".cloud-scene",{yPercent:-20,scale:1.13,ease:"none"},0).to(".hero-copy",{yPercent:-38,opacity:.06,filter:"blur(7px)",ease:"none"},0).to(".hero-footer",{y:-44,opacity:0,ease:"none"},0);gsap.timeline({scrollTrigger:{trigger:".identity",start:"top 82%",end:"bottom 12%",scrub:.16}}).from(".identity-kicker",{opacity:0,filter:"blur(6px)",y:28},.04).from(".identity-name",{opacity:0,filter:"blur(9px)",y:70},.08).from(".identity-roles span",{opacity:0,filter:"blur(4px)",y:22,stagger:.045},.2).to(".identity-copy",{yPercent:-28,ease:"none"},.64);gsap.timeline({scrollTrigger:{trigger:".about",start:"top 88%",end:"bottom 6%",scrub:.18}}).fromTo(".about-content",{y:100,opacity:.08,scale:.975},{y:-22,opacity:1,scale:1,ease:"none"},0).to(".about-content",{opacity:.24,filter:"blur(6px)",duration:.16,ease:"none"},.84);gsap.fromTo(".contact-approach i",{yPercent:24},{yPercent:-32,stagger:.08,ease:"none",scrollTrigger:{trigger:".contact-approach",start:"top bottom",end:"bottom top",scrub:.18}});gsap.fromTo(".contact-night-sky",{yPercent:-13,scale:1.1},{yPercent:12,scale:1.17,ease:"none",scrollTrigger:{trigger:".contact-approach",start:"top 70%",end:"bottom top",scrub:.18}})},root);return()=>ctx.revert()});let alive=true;document.fonts.ready.then(()=>{if(alive)ScrollTrigger.refresh()});return()=>{alive=false;media.revert()}},[]);
 return <div ref={root}>{loading&&<div className="sky-loader" role="status" aria-live="polite"><span className="loader-cloud" aria-hidden="true"/><p>WIZZBOT</p><small>ENTERING THE SKY</small></div>}<SmoothScroll/><CinematicDirector/><WorldAtmosphere/><a className="skip-link" href="#about">Skip to content</a><main>
  <div className="pre-featured-world"><div className="prelude-atmosphere" aria-hidden="true"><div className="prelude-sky-warm"/><div className="prelude-sky-cool"/><div className="prelude-light"/><div className="prelude-cloud-far"/><div className="prelude-cloud-near"/></div>
  <section className="hero" id="top"><CloudScene/><nav aria-label="Main navigation"><a className="brand" href="#top">WIZZ<span>BOT</span></a><button className="menu-toggle" type="button" aria-expanded={menu} aria-controls="navigation" onClick={()=>setMenu(!menu)}>Menu {menu?"−":"+"}</button><div id="navigation" className={menu?"nav-links is-open":"nav-links"}>{sections.map(([id,label])=><a key={id} href={`#${id}`} onClick={()=>setMenu(false)}>{label}</a>)}</div></nav><div className="hero-copy hero-intro"><p className="hero-tagline reveal">Building what feels impossible.</p><h1 className="reveal">WIZZ<span>BOT</span></h1></div><div className="hero-footer"><span>SCROLL TO ENTER</span><span aria-hidden="true">↓</span></div></section>
  <section className="identity" id="identity" aria-label="Introduction"><div className="identity-copy"><p className="identity-kicker">THE BUILDER BEHIND WIZZBOT</p><h2 className="identity-name">JITHIN</h2><div className="identity-roles">{["AI Engineer","Creative Developer","Full Stack Engineer","Hardware Builder","Product Designer","Creative Technologist"].map(role=><span key={role}>{role}</span>)}</div></div></section>
  <section className="section about" id="about"><div className="about-content"><p className="eyebrow">01 / ABOUT ME</p><div><h2>I build across the boundary of <em>ideas and systems.</em></h2><p>I’m a multidisciplinary builder working across AI, full-stack software, automation, connected hardware and interactive design. I like taking ambitious ideas from rough experiments to useful, expressive products.</p></div></div></section></div>
  <FeaturedBook/><ProjectJourney/>
  <div className="atmosphere-bridge contact-approach" aria-hidden="true"><i/><i/><i/></div>
  <section className="section contact" id="contact"><div className="contact-night-sky" aria-hidden="true"/><ContactPaper/><div className="contact-panel"><p className="eyebrow">04 / CONTACT</p><p>Have a strange, ambitious idea?</p><h2>Start a conversation.</h2>{contactLinks.length>0&&<nav className="contact-links" aria-label="Contact options">{contactLinks.map(([label,href])=><a href={href} key={label} target={href.startsWith("mailto:")?undefined:"_blank"} rel={href.startsWith("mailto:")?undefined:"noreferrer"}>{label}<span aria-hidden="true">↗</span></a>)}</nav>}<form onSubmit={e=>{e.preventDefault();if(!email)return;const data=new FormData(e.currentTarget);location.href=`mailto:${email}?subject=${encodeURIComponent("Portfolio inquiry from "+data.get("name"))}&body=${encodeURIComponent(String(data.get("message")))}`}}><label htmlFor="contact-name">Your name<input id="contact-name" name="name" autoComplete="name" required/></label><label htmlFor="contact-message">Your message<textarea id="contact-message" name="message" required rows={3}/></label><button type="submit" disabled={!email}>{email?"Open email draft ↗":"Contact details coming soon"}</button></form><p className="contact-note">{email?"Opens your email app with your message.":"Add your verified email and profile links to the environment to publish them here."}</p></div></section>
 </main><footer><span>WIZZBOT © {new Date().getFullYear()}</span><a href="#top">BACK TO SKY ↑</a><span>Made with intent</span></footer></div>}
