const fs=require("node:fs"),path=require("node:path");const root=path.resolve(__dirname,".."),src=path.join(root,"assets_from_threeui"),out=path.join(root,"public","threeui-native");
function extract(file,marker){const text=fs.readFileSync(path.join(src,file),"utf8"),at=text.indexOf(`### \`${marker}\``),f=text.indexOf("```",at),start=text.indexOf("\n",f)+1,end=text.indexOf("\n```",start);if(at<0||f<0||end<0)throw Error(marker);return text.slice(start,end)}
function swap(s,pairs){for(const[a,b]of pairs)s=s.split(a).join(b);return s}
fs.mkdirSync(out,{recursive:true});
let book=extract("book-for-featured-projects.md","public/landing-pages/bestsellers-book-showcase.html");
book=swap(book,[["Field Manuals — Tools for Thought","WizzBot — Featured Projects"],["Field Manuals home","WizzBot featured projects"],[">Field Manuals<",">WizzBot Projects<"],[">The Collection<",">Featured Projects<"],[">Agents<",">Systems<"],["Open Codex details","Open WizzBot v2 to v3 details"],["Open Claude Code details","Open Nocturnal AI Assistant details"],["Open Cursor details","Open XenoX details"],["Field Manual · I","Featured · I"],["Field Manual · II","Featured · II"],["Field Manual · III","Featured · III"],[">Codex<",">WizzBot<br>V2 → V3<"],[">Claude<br>Code<",">Nocturnal<"],[">Cursor<",">XenoX<"],["The Agentic Engineer","Connected Hardware"],["The Quiet Terminal","Personal Intelligence"],["The Augmented Editor","Agentic Automation"],["Systems · Tools · Taste","IoT · Devices · Prototypes"],["Context · Craft · Care","Memory · Identity · Automation"],["Select · Predict · Refine","UPCOMING · AI · EXECUTION"],[">Read<",">Explore<"],["Getting started","Inside the project"],["Your first prompt","Core focus"],["Before you ship","Project state"],["Field Notes","Project Notes"],["Field Edition","WizzBot Edition"],["Claude Code","Nocturnal AI Assistant"],["Codex","WizzBot v2 → v3"],["Cursor","XenoX"]]);
book=swap(book,[["Interactive AI coding field library","Interactive WizzBot featured project library"],["AI coding field manuals","WizzBot featured projects"]]);
book=book.replace(/const books = \{[\s\S]*?\r?\n      \};\r?\n\r?\n      const body/,`const books={codex:{title:"WizzBot v2 → v3",year:"Active",description:"The evolution of WizzBot as an IoT and hardware-focused system, exploring connected devices, physical interaction, and rapid prototyping.",steps:[{title:"Connected devices",body:"Hardware and software developed as one responsive system."}],prompt:"IoT · physical interaction · rapid prototyping",review:"An active evolution from v2 toward v3."},claude:{title:"Nocturnal AI Assistant",year:"Evolving",description:"A complete AI assistant evolved from a local chatbot into a full personal assistant with its own identity, memory, personality, redesigned interface, and automation capabilities.",steps:[{title:"Personal intelligence",body:"Memory, identity and personality make the assistant coherent."}],prompt:"AI · memory · personality · automation",review:"WizzBot's primary software and AI system."},cursor:{title:"XenoX",year:"UPCOMING",description:"An upcoming automation project focused on AI-driven application interaction and agentic task execution.",steps:[{title:"Agentic execution",body:"Application interaction coordinated through AI-driven workflows."}],prompt:"UPCOMING · automation · agents",review:"Currently being developed in focused sprints."}};\n\n      const body`);
fs.writeFileSync(path.join(out,"book.html"),book);
let film=extract("flimstrip-for-projects.md","src/shaders/character-carousel/sources/character-filmstrip.html");film=swap(film,[["Character Filmstrip","WizzBot Upcoming Work"],["Interactive editorial character filmstrip","WizzBot upcoming work filmstrip"]]);film=film.replace(/const profiles = \[[\s\S]*?\]\.map\(\(\[name, role, portrait\]\) => \(\{ name, role, portrait \}\)\);/,`const profiles=[["UPCOMING","Work in progress","sophie"],["UPCOMING","In development","marcus"],["UPCOMING","Exploration","julian"]].map(([name,role,portrait])=>({name,role,portrait}));`);fs.writeFileSync(path.join(out,"filmstrip.html"),film);
let paper=extract("3d-paper-for-contact.md","src/shaders/3d-paper/sources/3d-paper.html");paper=swap(paper,[["<title>3D Paper</title>","<title>WizzBot Contact Paper</title>"],["<h1>NOCTURNE</h1>","<h1>WIZZBOT</h1>"],["Studio of the Week.","LET\\'S BUILD."],["Feb 14, 2026","AI · SOFTWARE · HARDWARE"],["Nocturne Studio.","WizzBot."],["'By Nocturne Studio','Ilya Marchetti','Dara Okonkwo'","'AI Engineer','Creative Developer','Hardware Builder'"],["2026 Official Certificate.","MAKE CONTACT."],["The orbit jury is proud to declare this website Studio of the Week in recognition of the great talent and effort invested in its creation.","Have a strange, ambitious idea? Bring the possibility. Let\\'s make it real."],["SOTW","HELLO"],["orbit.","wizzbot."],[" winners"," portfolio"]]);fs.writeFileSync(path.join(out,"paper.html"),paper);console.log("Vendored canonical ThreeUI inner sources");
